"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, CalendarDays, CheckSquare, ChevronRight, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, Users, X } from "lucide-react";
import "./crm.css";

type Contact = { id:string; name:string; email:string|null; phone:string; kind:string; stage:string; source:string; notes:string; created_at:string };
type Case = { id:string; contact_id:string; title:string; area:string; number:string; status:string; description:string; visible_to_client?:number; updated_at:string };
type Task = { id:string; contact_id:string; case_id:string|null; title:string; due_at:string; done:number; visible_to_client?:number };
type Data = { role:"owner"|"staff"|"client"|"none"; email:string; contacts:Contact[]; cases:Case[]; tasks:Task[]; team?:{email:string}[] };
type View = "dashboard"|"leads"|"clients"|"cases"|"tasks"|"agenda"|"team";
type Entity = "contact"|"case"|"task"|"staff";
const stages = ["novo","em contato","proposta enviada","negociação","convertido"];
const empty:Data={role:"none",email:"",contacts:[],cases:[],tasks:[]};
const fmtDate=(value:string)=>value ? new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(value.slice(0,10)+"T12:00:00Z")):"Sem data";

export default function CrmApp({email,signOutPath}:{email:string;signOutPath:string}) {
  const [data,setData]=useState<Data>(empty), [view,setView]=useState<View>("dashboard"), [busy,setBusy]=useState(true), [error,setError]=useState(""), [notice,setNotice]=useState("");
  const [search,setSearch]=useState(""), [modal,setModal]=useState<Entity|null>(null), [editing,setEditing]=useState<Record<string,unknown>|null>(null), [mobileOpen,setMobileOpen]=useState(false);
  const [form,setForm]=useState<Record<string,unknown>>({});
  const reload=useCallback(async()=>{try{const response=await fetch("/api/crm",{cache:"no-store"});const body=await response.json() as Partial<Data>&{error?:string};if(!response.ok)throw new Error(body.error||"Falha ao carregar");setData({...empty,...body});setError("")}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar.")}finally{setBusy(false)}},[]);
  useEffect(()=>{void reload()},[reload]);
  const isStaff=data.role==="owner"||data.role==="staff";
  const contacts=data.contacts||[], cases=data.cases||[], tasks=data.tasks||[];
  const clientName=(id:string)=>contacts.find(c=>c.id===id)?.name||"Cliente";
  const matches=(...values:(string|null|undefined)[])=>values.some(v=>(v||"").toLowerCase().includes(search.toLowerCase()));
  const visibleContacts=useMemo(()=>contacts.filter(c=>matches(c.name,c.email,c.phone,c.stage,c.source)),[contacts,search]);
  const visibleCases=useMemo(()=>cases.filter(c=>matches(c.title,c.area,c.number,c.status,clientName(c.contact_id))),[cases,search,contacts]);
  const visibleTasks=useMemo(()=>tasks.filter(t=>matches(t.title,clientName(t.contact_id))),[tasks,search,contacts]);
  const open=(entity:Entity,record:Record<string,unknown>|null=null,defaults:Record<string,unknown>={})=>{setEditing(record);setForm(record?{...record,contactId:record.contact_id,caseId:record.case_id,dueAt:record.due_at,visibleToClient:!!record.visible_to_client}:defaults);setModal(entity);setNotice("");setError("")};
  const field=(key:string,value:unknown)=>setForm(f=>({...f,[key]:value}));
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(!modal)return;setBusy(true);try{const response=await fetch("/api/crm",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,entity:modal,id:editing?.id})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Não foi possível salvar");setModal(null);setEditing(null);setNotice("Registro salvo com sucesso.");await reload()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setBusy(false)}};
  const toggleTask=async(task:Task)=>{try{const response=await fetch("/api/crm",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity:"task",id:task.id,title:task.title,dueAt:task.due_at,done:!task.done,visibleToClient:!!task.visible_to_client})});if(!response.ok){const body=await response.json() as {error?:string};throw new Error(body.error||"Falha ao atualizar")}await reload()}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar")}};
  const nav: {id:View;label:string;icon:React.ComponentType<{size?:number}>}[] = [
    {id:"dashboard",label:"Visão geral",icon:LayoutDashboard},
    ...(isStaff?[{id:"leads" as View,label:"Leads",icon:BriefcaseBusiness},{id:"clients" as View,label:"Clientes",icon:Users}]:[]),
    {id:"cases",label:"Processos",icon:BriefcaseBusiness},{id:"tasks",label:"Tarefas",icon:CheckSquare},{id:"agenda",label:"Agenda",icon:CalendarDays},
    ...(data.role==="owner"?[{id:"team" as View,label:"Equipe",icon:Settings}]:[]),
  ];
  const switchView=(next:View)=>{setView(next);setMobileOpen(false);setSearch("");setError("")};
  if(busy && !data.email)return <main className="crm-loading">Carregando área protegida...</main>;
  if(error && !data.email)return <main className="crm-access"><div><span className="crm-monogram">RA</span><h1>Não foi possível abrir o CRM</h1><p>{error}</p><button className="crm-primary" onClick={()=>{setBusy(true);void reload()}}>Tentar novamente</button></div></main>;
  if(data.role==="none")return <main className="crm-access"><div><span className="crm-monogram">RA</span><p className="crm-eyebrow">RAMOS ADVOCACIA</p><h1>Acesso ainda não vinculado</h1><p>Você entrou como <strong>{data.email||email}</strong>. Peça à equipe que cadastre este mesmo e-mail como cliente ou integrante do escritório.</p><a className="crm-primary" href="mailto:contato@ramoseacbas.com.br?subject=Acesso%20ao%20CRM">Solicitar vínculo</a><a className="crm-secondary" href={signOutPath}>Trocar de conta</a></div></main>;
  return <div className="crm-shell">
    <aside className={"crm-sidebar "+(mobileOpen?"open":"")}><div className="crm-brand"><span className="crm-mark">RA</span><span><strong>RAMOS</strong><small>ADVOCACIA</small></span></div><p className="crm-side-caption">{isStaff?"GESTÃO DO ESCRITÓRIO":"SEU ESPAÇO"}</p><nav aria-label="Navegação do CRM">{nav.map(item=><button key={item.id} type="button" className={view===item.id?"active":""} onClick={()=>switchView(item.id)}><item.icon size={18}/>{item.label}</button>)}</nav><div className="crm-side-bottom"><span>{isStaff?"Painel protegido da equipe":"Acesso privado do cliente"}</span><a href="/">Voltar ao site</a></div></aside>
    <div className="crm-main"><header className="crm-top"><button className="crm-mobile-menu" aria-label="Abrir menu" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={22}/></button><div className="crm-search"><Search size={18}/><input aria-label="Buscar registros" placeholder="Buscar clientes, processos e tarefas..." value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="crm-account">{email}</span><a href={signOutPath} title="Sair" aria-label="Sair"><LogOut size={18}/></a></header>
      <main className="crm-content">
        <div className="crm-pagehead"><div><p className="crm-eyebrow">{isStaff?"RAMOS ADVOCACIA · CRM":"ÁREA DO CLIENTE"}</p><h1>{({dashboard:isStaff?"Visão geral":"Seu atendimento",leads:"Leads",clients:"Clientes",cases:"Processos",tasks:"Tarefas",agenda:"Agenda",team:"Equipe"} as Record<View,string>)[view]}</h1><p>{isStaff?"Acompanhe os registros do escritório em um só lugar.":"Acompanhe as informações compartilhadas pela equipe."}</p></div>{isStaff&&view!=="dashboard"&&view!=="agenda"&&<button className="crm-primary" onClick={()=>open(view==="leads"||view==="clients"?"contact":view==="cases"?"case":view==="tasks"?"task":"staff",null,view==="clients"?{kind:"client"}:view==="leads"?{kind:"lead"}:{})}><Plus size={17}/> Novo {view==="leads"?"lead":view==="clients"?"cliente":view==="cases"?"processo":view==="tasks"?"compromisso":"integrante"}</button>}</div>
        {error&&<div className="crm-error" role="alert">{error}</div>}{notice&&<div className="crm-notice" role="status">{notice}</div>}
        {view==="dashboard"&&<><div className="crm-kpis"><div><span>{isStaff?"Leads":"Processos"}</span><strong>{isStaff?contacts.filter(c=>c.kind==="lead").length:cases.length}</strong><small>{isStaff?"Oportunidades cadastradas":"Compartilhados com você"}</small></div><div><span>{isStaff?"Clientes":"Compromissos"}</span><strong>{isStaff?contacts.filter(c=>c.kind==="client").length:tasks.filter(t=>!t.done).length}</strong><small>{isStaff?"Clientes ativos no cadastro":"Tarefas em aberto"}</small></div><div><span>{isStaff?"Processos":"Concluídos"}</span><strong>{isStaff?cases.length:tasks.filter(t=>t.done).length}</strong><small>{isStaff?"Casos registrados":"Compromissos finalizados"}</small></div><div><span>Tarefas pendentes</span><strong>{tasks.filter(t=>!t.done).length}</strong><small>Para acompanhar</small></div></div><div className="crm-dashboard-grid"><section className="crm-panel"><div className="crm-panel-head"><h2>{isStaff?"Funil de oportunidades":"Seus processos"}</h2><button onClick={()=>switchView(isStaff?"leads":"cases")}>Ver todos <ChevronRight size={15}/></button></div>{isStaff?<div className="crm-pipeline">{stages.slice(0,4).map(stage=><div key={stage}><h3>{stage}<span>{contacts.filter(c=>c.kind==="lead"&&c.stage===stage).length}</span></h3>{contacts.filter(c=>c.kind==="lead"&&c.stage===stage).slice(0,3).map(c=><button key={c.id} onClick={()=>open("contact",c as unknown as Record<string,unknown>)}><strong>{c.name}</strong><small>{c.source||"Sem origem"}</small></button>)}</div>)}</div>:<div className="crm-list">{cases.length?cases.map(c=><article key={c.id}><strong>{c.title}</strong><span>{c.status}</span></article>):<p className="crm-empty">Nenhum processo compartilhado ainda.</p>}</div>}</section><section className="crm-panel"><div className="crm-panel-head"><h2>Próximos compromissos</h2><button onClick={()=>switchView("agenda")}>Ver agenda <ChevronRight size={15}/></button></div><div className="crm-list">{tasks.filter(t=>!t.done).slice(0,5).map(t=><article key={t.id}><div><strong>{t.title}</strong><small>{isStaff?clientName(t.contact_id):"Compartilhado com você"}</small></div><span>{fmtDate(t.due_at)}</span></article>)}{!tasks.some(t=>!t.done)&&<p className="crm-empty">Nenhum compromisso pendente.</p>}</div></section></div></>}
        {(view==="leads"||view==="clients")&&<section className="crm-panel"><div className="crm-panel-head"><h2>{view==="leads"?"Oportunidades":"Pessoas atendidas"}</h2><span>{visibleContacts.filter(c=>c.kind===(view==="leads"?"lead":"client")).length} registros</span></div><div className="crm-table-wrap"><table><thead><tr><th>Nome</th><th>Contato</th><th>{view==="leads"?"Etapa":"Situação"}</th><th>Origem</th><th></th></tr></thead><tbody>{visibleContacts.filter(c=>c.kind===(view==="leads"?"lead":"client")).map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email||c.phone||"—"}</td><td><span className="crm-badge">{c.stage}</span></td><td>{c.source||"—"}</td><td><button className="crm-row-action" onClick={()=>open("contact",c as unknown as Record<string,unknown>)}>Abrir</button></td></tr>)}</tbody></table></div>{!visibleContacts.some(c=>c.kind===(view==="leads"?"lead":"client"))&&<p className="crm-empty">Nenhum registro encontrado. Use “Novo” para começar.</p>}</section>}
        {view==="cases"&&<section className="crm-panel"><div className="crm-panel-head"><h2>Processos jurídicos</h2><span>{visibleCases.length} registros</span></div><div className="crm-list crm-case-list">{visibleCases.map(c=><article key={c.id}><div><strong>{c.title}</strong><small>{isStaff?clientName(c.contact_id)+" · ":""}{c.area||"Área não informada"}{c.number?" · "+c.number:""}</small></div><span className="crm-badge">{c.status}</span>{isStaff&&<button className="crm-row-action" onClick={()=>open("case",c as unknown as Record<string,unknown>)}>Editar</button>}</article>)}{!visibleCases.length&&<p className="crm-empty">Nenhum processo disponível.</p>}</div></section>}
        {(view==="tasks"||view==="agenda")&&<section className="crm-panel"><div className="crm-panel-head"><h2>{view==="agenda"?"Compromissos por data":"Lista de tarefas"}</h2><span>{visibleTasks.length} registros</span></div><div className="crm-list crm-task-list">{[...visibleTasks].sort((a,b)=>(a.due_at||"9999").localeCompare(b.due_at||"9999")).map(t=><article key={t.id}><div className="crm-task-title">{isStaff&&<input type="checkbox" checked={!!t.done} onChange={()=>void toggleTask(t)} aria-label={"Concluir "+t.title}/>}<div><strong className={t.done?"done":""}>{t.title}</strong><small>{isStaff?clientName(t.contact_id):"Seu compromisso"}</small></div></div><span>{fmtDate(t.due_at)}</span>{isStaff&&<button className="crm-row-action" onClick={()=>open("task",t as unknown as Record<string,unknown>)}>Editar</button>}</article>)}{!visibleTasks.length&&<p className="crm-empty">Nenhum compromisso disponível.</p>}</div></section>}
        {view==="team"&&data.role==="owner"&&<section className="crm-panel"><div className="crm-panel-head"><h2>Acesso da equipe</h2></div><p className="crm-panel-intro">Cadastre o e-mail usado pelo integrante para entrar. O acesso às informações dos clientes começa após o vínculo.</p><div className="crm-list">{data.team?.map(m=><article key={m.email}><strong>{m.email}</strong><span>Equipe</span></article>)}{!data.team?.length&&<p className="crm-empty">Nenhum integrante cadastrado.</p>}</div></section>}
      </main>
    </div>
    {modal&&<div className="crm-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="crm-modal" role="dialog" aria-modal="true" aria-label={editing?"Editar registro":"Novo registro"}><header><div><p className="crm-eyebrow">RAMOS ADVOCACIA</p><h2>{editing?"Editar":"Novo"} {modal==="contact"?(form.kind==="client"?"cliente":"lead"):modal==="case"?"processo":modal==="task"?"compromisso":"integrante"}</h2></div><button aria-label="Fechar" onClick={()=>setModal(null)}><X size={20}/></button></header><form onSubmit={save}>
      {modal==="contact"&&<><label>Nome<input required value={String(form.name||"")} onChange={e=>field("name",e.target.value)}/></label><div className="crm-form-grid"><label>E-mail<input type="email" value={String(form.email||"")} onChange={e=>field("email",e.target.value)}/></label><label>Telefone<input value={String(form.phone||"")} onChange={e=>field("phone",e.target.value)}/></label></div><div className="crm-form-grid"><label>Tipo<select value={String(form.kind||"lead")} onChange={e=>field("kind",e.target.value)}><option value="lead">Lead</option><option value="client">Cliente</option></select></label><label>Etapa<select value={String(form.stage||"novo")} onChange={e=>field("stage",e.target.value)}>{stages.map(s=><option key={s} value={s}>{s}</option>)}</select></label></div><label>Origem<input placeholder="Indicação, site, telefone..." value={String(form.source||"")} onChange={e=>field("source",e.target.value)}/></label><label>Observações<textarea rows={3} value={String(form.notes||"")} onChange={e=>field("notes",e.target.value)}/></label><p className="crm-form-hint">Para liberar o portal do cliente, use o mesmo e-mail da conta com que ele entrará e selecione “Cliente”.</p></>}
      {modal==="case"&&<><label>Cliente<select required value={String(form.contactId||"")} onChange={e=>field("contactId",e.target.value)} disabled={!!editing}><option value="">Selecione um cliente</option>{contacts.filter(c=>c.kind==="client").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Título<input required value={String(form.title||"")} onChange={e=>field("title",e.target.value)}/></label><div className="crm-form-grid"><label>Área<input placeholder="Cível, trabalhista..." value={String(form.area||"")} onChange={e=>field("area",e.target.value)}/></label><label>Número do processo<input value={String(form.number||"")} onChange={e=>field("number",e.target.value)}/></label></div><label>Situação<select value={String(form.status||"em andamento")} onChange={e=>field("status",e.target.value)}>{["em andamento","aguardando","audiência","concluído","arquivado"].map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>Descrição<textarea rows={3} value={String(form.description||"")} onChange={e=>field("description",e.target.value)}/></label><label className="crm-check"><input type="checkbox" checked={!!form.visibleToClient} onChange={e=>field("visibleToClient",e.target.checked)}/> Compartilhar este processo no portal do cliente</label></>}
      {modal==="task"&&<><label>Cliente<select required value={String(form.contactId||"")} onChange={e=>field("contactId",e.target.value)} disabled={!!editing}><option value="">Selecione um contato</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tarefa ou compromisso<input required value={String(form.title||"")} onChange={e=>field("title",e.target.value)}/></label><label>Data<input type="date" value={String(form.dueAt||"").slice(0,10)} onChange={e=>field("dueAt",e.target.value)}/></label>{!!editing&&<label className="crm-check"><input type="checkbox" checked={!!form.done} onChange={e=>field("done",e.target.checked)}/> Concluída</label>}<label className="crm-check"><input type="checkbox" checked={!!form.visibleToClient} onChange={e=>field("visibleToClient",e.target.checked)}/> Mostrar no portal do cliente</label></>}
      {modal==="staff"&&<label>E-mail do integrante<input type="email" required value={String(form.email||"")} onChange={e=>field("email",e.target.value)}/></label>}
      {error&&<p className="crm-error" role="alert">{error}</p>}<footer><button type="button" className="crm-cancel" onClick={()=>setModal(null)}>Cancelar</button><button type="submit" className="crm-primary" disabled={busy}>{busy?"Salvando...":"Salvar registro"}</button></footer>
    </form></div></div>}
  </div>;
}
